language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

env: TMPDIR=/tmp

install:
 - phpenv rehash

services:
  - memcached
  - mysql
  - postgresql

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then travis_retry composer self-update; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "5.2" ]]; then travis_retry composer install --no-interaction --prefer-source --dev; fi
  
  - mysql -e 'create database zftest;'
  - psql -c 'create database zftest;' -U postgres

  - phpenv config-add tests/php7_config.ini

  - cp ./tests/TestConfiguration.travis.php ./tests/TestConfiguration.php

script:
 - cd tests/
 - php runalltests.php
 
matrix:
  allow_failures:
   - php: 7.4
